# Generated by Django 4.2.3 on 2023-08-01 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera_Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('interes_mora', models.IntegerField(blank=True, null=True, verbose_name='Interes')),
                ('imp_med_amb', models.IntegerField(blank=True, null=True, verbose_name='Impuesto')),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('descuento', models.IntegerField(blank=True, null=True, verbose_name='Interes')),
                ('total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cedula')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido')),
                ('celular', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.FloatField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tarifa')),
                ('Valor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('cedula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.cliente')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('codigo_pro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.propiedad')),
                ('codigo_tar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.tarifa')),
            ],
            options={
                'verbose_name': 'Medidor',
                'verbose_name_plural': 'Medidores',
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lec', models.DateTimeField(null=True)),
                ('periodo_consumo', models.DurationField(blank=True, null=True)),
                ('lec_anterior', models.DateTimeField(null=True)),
                ('lec_actual', models.DateTimeField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('Num_med', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.medidor')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio_unit', models.FloatField(blank=True, null=True)),
                ('Precio_total', models.FloatField(blank=True, null=True)),
                ('codigo_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.concepto')),
                ('codigo_lec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.lectura')),
                ('medidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.medidor')),
                ('numero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.cabecera_planilla')),
            ],
        ),
        migrations.AddField(
            model_name='cabecera_planilla',
            name='cedula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.cliente'),
        ),
    ]
